
server:
  port: 50012

es:
  ip:
    # 这里 你的 elasticsearch ip
    host: 10.0.1.174
    # 这里 你的 elasticsearch 端口
    port: 9210
  #  --------------------- 备份数据 -------------------------------
  # 对应 elasticsearch.yml 的  path.repo 路径
  back:
    location: D:/hbdata2/snapshot
  #  --------------------- 恢复数据 --------------------------------
  #  true 为 恢复数据,false 为 备份数据,默认为 false
  lock: true