
server:
  port: 50012

es:
  ip:
    # 这里 你的  ip:端口
    host: 10.0.1.91
    # 这里 你的  端口
    port: 9200
  back:
    location: /usr/local/elasticsearch/snapshot
  # 注意  true 为 恢复数据,false 为 备份数据,默认为 false
  lock: true